package locators;

import java.util.Arrays;
import java.util.List;

public class MaterialsPageLocators {

    /** xpath */ public static final String MATERIALS_HEADING = "//h4[normalize-space()='Materials']";
    /** xpath */ public static final String MASTER_SIDE_MENU = "//span[contains(text(),'Master')]/..//span[1]";
    /** linkText */ public static final String MATERIALS_SIDE_MENU = "Materials";
    /** xpath */ public static final String DELETE_BUTTON = "//h4[normalize-space()='Materials']/../../../following-sibling::div[2]//button[contains(text(),'Delete')]";
    /** xpath */ public static final String DELETE_POPUP = "//div[@class='modal-title h4' and contains(text(),'Confirm Delete')]";
    /** xpath */ public static final String DELETE_POPUP_CANCEL = "//div[@class='modal-title h4']/../following-sibling::div[2]//button[1]";
    /** xpath */ public static final String DELETE_POPUP_CONFIRM = "//div[@class='modal-title h4']/../following-sibling::div[2]//button[2]";
    /** xpath */ public static final String ADD_BUTTON = "//h4[normalize-space()='Materials']/../../../following-sibling::div[2]//span[contains(text(),'Add')]";
    /** xpath */ public static final String ADD_POPUP = "//div[@class='modal-title h4' and contains(text(),'Add Material')]";
    /** xpath */ public static final String ADD_POPUP_CANCEL = "//div[@class='modal-title h4']/../following-sibling::div[3]//button[1]";
    /** xpath */ public static final String ADD_POPUP_SAVE = "//div[@class='modal-title h4']/../following-sibling::div[3]//button[2]";
    /** xpath */ public static final String FILTER_BUTTON = "//h4[normalize-space()='Materials']/../../../following-sibling::div[2]//a";
    /** xpath */ public static final String FILTER_SEARCH_BUTTON = "//label[contains(text(),'Search')]/../following-sibling::div//input[1]";
    /** xpath */ public static final String TABLE_FIRST_ROW_PRICE_HISTORY = "//div[@role='rowgroup'][2]//div[@role='row'][1]//div[6]//button[2]";
    /** xpath */ public static final String TABLE_FIRST_ROW_MATERIAL_CODE = "//div[@role='rowgroup'][2]//div[@role='row'][1]//div[2]//div";
    /** xpath */ public static final String TABLE_FIRST_ROW_MATERIAL_NAME = "//div[@role='rowgroup'][2]//div[@role='row'][1]//div[3]//div";
    /** xpath */ public static final String TABLE_FIRST_ROW_PRICE = "//div[@role='rowgroup'][2]//div[@role='row'][1]//div[5]//div";
    /** xpath */ public static final String TABLE_FIRST_ROW_EDIT_ICON = "//div[@role='rowgroup'][2]//div[@role='row'][1]//div[6]//button[1]";
    /** xpath */ public static final String TABLE_FIRST_ROW_DELETE_ICON = "//div[@role='rowgroup'][2]//div[@role='row'][1]//div[6]//button[3]";
    /** xpath */ public static final String PRICE_HISTORY_HEADING = "//h4[contains(text(),'Material Price')]";
    /** id */ public static final String FILTER_SEARCH_FIELD = "search";
    /** id */ public static final String ADD_MATERIAL_CODE_FIELD = "material_code";
    /** id */ public static final String ADD_MATERIAL_NAME_FIELD = "material_name";
    /** xpath */ public static final String HOME_PAGE_LOGO = "//i[@class='feather icon-home']";
    /** xpath */ public static final String EMPTY_RECORD = "//div[contains(text(),'There are no records to display')]";
    /** xpath */ public static final String RESET_BUTTON = "//input[@value='Reset']";
    /** xpath */ public static final String SELECT_UOM_DROPDOWN = "//label[@for='uom']/following-sibling::div";
    /** id */ public static final String ADD_MATERIAL_PRICE = "material_price";
    /** xpath */ public static final String MATERIAL_CREATED_MESSAGE = "//div[contains(text(), 'Material Created Successfully')]";
    /** xpath */ public static final String MATERIAL_DELETED_MESSAGE = "//div[contains(text(), 'Material deleted successfully!')]";
    /** xpath */ public static final String MATERIAL_CODE_ERROR = "//input[@id='material_code']/following-sibling::div";
    /** xpath */ public static final String MATERIAL_NAME_ERROR = "//input[@id='material_name']/following-sibling::div";
    /** xpath */ public static final String UOM_DROPDOWN_ERROR = "//label[@for='uom']/following-sibling::div[2]";
    /** xpath */ public static final String MATERIAL_PRICE_ERROR = "//input[@id='material_price']/following-sibling::div";
    /** xpath */ public static final String UOM_DROPDOWN_SELECTED_OPTION = "//div[@id='uom_id']//input[@type='text']/..//parent::div//div[1]";
    /** xpath */ public static final String TABLE_TOTAL_DELETE_ICON = "//div[@role='rowgroup'][2]//div[@role='row']//div[6]//button[3]";
    /** xpath */ public static final String DELETE_POPUP_TEXT = "//div[@class='modal-title h4']/../following-sibling::div//p";
    /** xpath */ public static final String EDIT_POPUP_UPDATE_BTN = "//div[@class='modal-title h4']/../following-sibling::div[3]//button[2]";
    /** xpath */ public static final String ALERT_POPUP = "//div[@role='alert']//div[2]";
    /** xpath */ public static final String MATERIAL_PRICE_PAGE_MAT_PRICE = "//div[@role='rowgroup'][2]//div[@role='row'][1]//div[4]//div";
    /** xpath */ public static final String MATERIAL_PRICE_PAGE_ADD_BTN = "//h4[normalize-space()='Material Price']/../../../following-sibling::div[3]//span[contains(text(),'Add')]";
    /** id */ public static final String ADD_MATERIAL_PRICE_DATE = "datepicker";
    /** xpath */ public static final String CURRENT_DATE = "//div[@aria-current='date']";
    /** xpath */ public static final String BACK_BUTTON = "//button[text()='Back']";
    /** xpath */ public static final String MATERIAL_PRICE_TABLE_FIRST_ROW_DELETE = "//div[@role='rowgroup'][2]//div[@role='row'][1]//div[5]//button[2]";
    /** xpath */ public static final String MATERIAL_PRICE_TABLE_FIRST_ROW_EDIT = "//div[@role='rowgroup'][2]//div[@role='row'][1]//div[5]//button[1]";
    /** xpath */ public static final String MATERIAL_PRICE_FILTER_BUTTON = "//a[contains(text(),' Filter')]";
    /** xpath */ public static final String MATERIAL_PRICE_TABLE_FIRST_ROW_DATE = "//div[@role='rowgroup'][2]//div[@role='row'][1]//div[2]//div";
    /** id */ public static final String MATERIAL_PRICE_FILTER_SEARCH_FIELD = "search";
    /** xpath */ public static final String MATERIAL_PRICE_FILTER_SEARCH_BTN = "//form[@id='searchHistoryForm']//div//div[2]//input[1]";
    /** xpath */ public static final String MATERIAL_CODE_HEADER = "//div[normalize-space()='Material Code']";
    /** xpath */ public static final String MATERIAL_NAME_HEADER = "//div[normalize-space()='Material Name']";
    /** xpath */ public static final String TABLE_ALL_MATERIAL_NAME = "//div[@role='rowgroup'][2]//div[@role='row']//div[3]//div";
    /** xpath */ public static final String TABLE_ALL_MATERIAL_CODE = "//div[@role='rowgroup'][2]//div[@role='row']//div[2]//div";
    /** xpath */ public static final String MATERIAL_PRICE_DATE_ERROR = "//span[@class='error-message-unique']";
    /** xpath */ public static final String MATERIALS_ROWS_PER_PAGE = "//select[@aria-label='Rows per page:']";
    /** xpath */ public static final String UOM_HEADER = "//div[normalize-space()='UOM']";
    /** xpath */ public static final String TABLE_ALL_UOM = "//div[@role='rowgroup'][2]//div[@role='row']//div[4]//div";
    /** xpath */ public static final String LATEST_PRICE_HEADER = "//div[normalize-space()='Latest Price']";
    /** xpath */ public static final String TABLE_ALL_LATEST_PRICE = "//div[@role='rowgroup'][2]//div[@role='row']//div[5]//div";
    /** xpath */ public static final String TOTAL_ITEMS_COUNT = "//span[contains(text(),'Rows per page:')]/..//span[2]";

    public static final String SEARCHED_PAGINATION_COUNT = "1-1 of 1";
    public static final String MATERIAL_CODE = "M999";
    public static final String MATERIAL_NAME = "Test Material";
    public static final String MATERIAL_PRICE = "10";
    public static final String MATERIAL_CODE_ERROR_MSG = "Please enter material code.";
    public static final String MATERIAL_NAME_ERROR_MSG = "Please enter material name.";
    public static final String UOM_ERROR_MSG = "Please select UOM.";
    public static final String MATERIAL_PRICE_ERROR_MSG = "Please enter material price.";
    public static final String LIMIT_CHECK = "EIE9R8U3K7493JDKEIE9R8U3KR8U3KIE9R8U3KR8U3K3KR9R8U3K74";
    public static final String MAX_LENGTH_ERROR = "Maximum length should be 50 characters.";
    public static final String DUPLICATE_MATERIAL_CODE_ERROR = "Material Code already exists.";
    public static final String DUPLICATE_MATERIAL_NAME_ERROR = "Material Name already exists.";
    public static final List<String> VALID_UOM_OPTIONS = Arrays.asList("kilogram", "Liters", "Milli grams", "Inches", "Hours", "Pound");
    public static final String DELETE_POPUP_TEXT_MSG = "Are you sure you want to delete the material Tensile's? This action cannot be undone. Click 'Yes, Delete' to proceed or 'Cancel' if you have changed your mind.";
    public static final String SECOND_MATERIAL_CODE = "M999M";
    public static final String SECOND_MATERIAL_NAME = "Second Test Material";
    public static final String UPDATE_MESSAGE = "Material Details Updated Successfully.";
    public static final String RED_COLOR_VALUE = "rgba(255, 0, 0, 1)";
    public static final String PRICE_DETAILS_UPDATE_MESSAGE = "Material Price Details Updated Successfully.";
    public static final String DUPLICATE_DATE_ERROR = "Material Price Date already exists.";
    public static final String DATE_PICKER_FORMAT = "DD/MM/YYYY";
    public static final String INVALID_MATERIAL_NAME = "@#$123";
    public static final String INVALID_MATERIAL_CODE = "123&*(";
    public static final String INVALID_MATERIAL_CODE_ERROR = "Please enter valid Material Code";
    public static final String INVALID_MATERIAL_NAME_ERROR = "Please enter valid Material Name";
}
